server:
  port: 8080

spring:
  application:
    name: db_project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_hose
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update

