server:
  port: 8080

spring:
  application:
    name: db_project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: yuchan
    password: 1092
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update

